### ISSUE TITLE
Stable versions and changelogs

### ISSUE THREAD

**Issue by nicokaiser** [jaredwray/keyv#1202]
This project seems to be moving fast, which is a good thing. However for people using the cacheable / keyv libraries this is a huge headache, since we are constantly getting new major versions and there is no good way to see which change requires a semver-major change.

So my wish would be to

1. have proper per-package changelogs which make it possible to figure out which changes were made and which adjustments in the code are required on semver-major version bumps. Currently it is a huge guessing game.

2. have more stable versions. I know this might get better in the future, but during the last few months we had to completely rewrite everything caching-related multiple times due to changes in cache-manager/cacheable/keyv/yet/... Maybe these packages need to be flagged as beta versions somewhere so users can wait for the breaking changes to settle until upgrading.

**Comment by jaredwray** [comment]
@nicokaiser - thanks for the request and we have looked at this but decided against it because of the overhead to manage with auto-generating the changelog. I will add it to the list for later this year to look at. 

There have been a couple of breaking changes with redis and with valkey as ioredis is no longer supported. Most of our plans for the rest of the year are to be additive and not do breaking changes. Sorry for the inconvenience. 

Would love to hear more about your project and what you are using Keyv for!
