### ISSUE TITLE
difference between @types/keyv and types of keyv

### ISSUE THREAD

**Issue by AnWeber** [jaredwray/keyv#268]
With https://github.com/jaredwray/keyv/pull/257 typescript support was implemented. I love it and support it. However, this was a breaking change in my eyes. The types differ between [@types/keyv](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/6963e48c635515344d0f1259cfdecb163390cf4e/types/keyv/index.d.ts) and [keyv](https://github.com/jaredwray/keyv/blob/main/packages/keyv/src/index.d.ts) package. 
I use `keyv` myself only as transitive dependency via the `cachable-request`. This imports keyv via [`>4.0.0`](https://github.com/lukechilds/cacheable-request/blob/master/package.json#L35). After `npm upgrade` I get this error.

```
node_modules/@types/cacheable-request/index.d.ts:13:10 - error TS2305: Module '"keyv"' has no exported member 'Store'.

13 import { Store } from 'keyv';
```

typescript prioritize the shipped types over types provided with ' @types/...'.  Would it be possible to add the missing types, or is this not desired (could provide pr)? Another solution would be to update to a new major version and revert the change in v4.x.x

**Comment by jaredwray** [comment]
@AnWeber - Please stay on 4.1.1 until we fix the Store issue we are seeing which we believe should be resolved shortly. 

you can follow along here also: https://github.com/jaredwray/keyv/pull/267

**Comment by AnWeber** [comment]
@jaredwray I saw the PR, but unfortunately did not realize that the exact problem was also being discussed. Cool, thanks.

**Comment by jaredwray** [comment]
@AnWeber Thanks. We are working on it.

**Comment by jaredwray** [comment]
@AnWeber wanted to check in that the 4.2.1 release is working for you

**Comment by AnWeber** [comment]
@jaredwray Works for me too. Thank you.

**Comment by trevor-scheer** [comment]
@jaredwray I landed a change to @types/keyv recently that isn't accounted for in the new type definitions. I think that it makes sense for a partial of `Keyv.opts` to be available to classes that `extend Keyv`, since `this.opts` is always assigned in the Keyv constructor. In hindsight, I should've made it a `protected` property, but I'm curious to hear your thoughts and if you'd accept a PR with changes in the spirit of this one: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59154

Thanks!
