### ISSUE TITLE
Last version to use sqlite3

### ISSUE THREAD

**Issue by TheCuteFoxxy** [jaredwray/keyv#286]
What is the last version to support sqlite3? better-sqlite3 does not support `<db>.opts.store.query` and has broken large portions of my projects due to this. 

Trying to find out the last version(s) of keyv and keyv/sqlite that used sqlite3 rather than better-sqlite3.

Related to #221

**Comment by jaredwray** [comment]
Hi @TheCuteFoxxy - we are currently looking into sqlite3 vs better-sqlite3 as many people have complained about it. Version  `2.0.0` was the latest with this and you can still use that. 

Our current plan that we are looking at is to move back to sqlite3 in `@keyv/sqlite` because of all the internal breakage with better. This could happen over the next 30 days.

**Comment by TheCuteFoxxy** [comment]
Can you specific the version to use for the storage adapter, attempting to install version `2.0.0` of `@sqlite/keyv` causes gyp error(s).

**Comment by jaredwray** [comment]
@TheCuteFoxxy that should be the one that would work. If not, We will have a newer version of sqlite coming in the next week or so that should be based on sqlite3. FYI.

**Comment by jaredwray** [comment]
This should be resolved with the following version `v3.5.0`: https://www.npmjs.com/package/@keyv/sqlite
